services:
  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"

  character-db:
    image: postgres:15
    container_name: character-db
    environment:
      POSTGRES_DB: character_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  combat-db:
    image: postgres:15
    container_name: combat-db
    environment:
      POSTGRES_DB: combat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"    

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  account-service:
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    container_name: account-service
    ports:
      - "3001:3000"
    env_file: ./services/account-service/.env
    volumes:
      - .:/app
      - /app/services/account-service/node_modules
      - /app/shared/node_modules
    depends_on:
      - account-db

  character-service:
    build:
      context: .
      dockerfile: services/character-service/Dockerfile
    container_name: character-service
    ports:
      - "3002:3000"
    env_file: ./services/character-service/.env
    volumes:
      - .:/app
      - /app/services/character-service/node_modules
      - /app/shared/node_modules
    depends_on:
      - character-db
      - redis

  combat-service:
    build:
      context: .
      dockerfile: services/combat-service/Dockerfile
    container_name: combat-service
    ports:
      - "3003:3000"
    env_file: ./services/combat-service/.env
    volumes:
      - .:/app
      - /app/services/combat-service/node_modules
      - /app/shared/node_modules
    depends_on:
      - combat-db
      - redis